write_crop_aquacrop <-
function(path, cultivar, crop_params_aquacrop, NPLDS = 150000){


### Inicia la creacion del archivo CRO

sink(paste0(path, "/", cultivar, ".CRO"), append = F)


### Info data
cat(paste(cultivar, "AquaCrop CRO  by https://github.com/jrodriguez88"), sep = '\n')
cat("     6.1       : AquaCrop Version (May 2018)", sep = '\n')
cat("     1         : File not protected", sep = '\n')
cat("     2         : fruit/grain producing crop", sep = '\n')
cat("     1         : Crop is sown", sep = '\n')
cat("     0         : Determination of crop cycle : by growing degree-days", sep = '\n')
cat("     1         : Soil water depletion factors (p) are adjusted by ETo", sep = '\n')
cat("     8.0       : Base temperature (oC) below which crop development does not progress", sep = '\n')
cat("    30.0       : Upper temperature (oC) above which crop development no longer increases with an increase in temper", sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_M),"         : Total length of crop cycle in growing degree-days"), sep = '\n')
cat("     0.00      : Soil water depletion factor for canopy expansion (p-exp) - Upper threshold", sep = '\n')
cat(paste0(sprintf("     %1.2f", crop_params_aquacrop$Ks_exp),"      : Soil water depletion factor for canopy expansion (p-exp) - Lower threshold"), sep = "\n")
cat("     3.0       : Shape factor for water stress coefficient for canopy expansion (0.0 = straight line)", sep = '\n')
cat("     0.50      : Soil water depletion fraction for stomatal control (p - sto) - Upper threshold", sep = '\n')
cat("     3.0       : Shape factor for water stress coefficient for stomatal control (0.0 = straight line)", sep = '\n')
cat("     0.55      : Soil water depletion factor for canopy senescence (p - sen) - Upper threshold", sep = '\n')
cat("     3.0       : Shape factor for water stress coefficient for canopy senescence (0.0 = straight line)", sep = '\n')
cat("     0         : Sum(ETo) during stress period to be exceeded before senescence is triggered", sep = '\n')
cat("     0.75      : Soil water depletion factor for pollination (p - pol) - Upper threshold", sep = '\n')
cat("     0         : Pct Vol for Anaerobiotic point ( (SAT - [vol-pct]) at which deficient aeration occurs )", sep = '\n')
cat("    50         : Considered soil fertility stress for calibration of stress response (Percent)", sep = '\n')
cat("    25.00      : Response of canopy expansion is not considered", sep = '\n')
cat("    25.00      : Response of maximum canopy cover is not considered", sep = '\n')
cat("    25.00      : Response of crop Water Productivity is not considered", sep = '\n')
cat("    25.00      : Response of decline of canopy cover is not considered", sep = '\n')
cat("    -9         : dummy - Parameter no Longer required", sep = '\n')
cat(paste0(sprintf("     %1.0f", crop_params_aquacrop$Ks_polc), "         : Minimum air temperature below which pollination starts to fail (cold stress) (oC)"), sep = '\n')
cat(paste0(sprintf("    %1.0f", crop_params_aquacrop$Ks_polh), "         : Maximum air temperature above which pollination starts to fail (heat stress) (oC)"), sep = '\n')
cat("    10.0       : Minimum growing degrees required for full crop transpiration (oC - day)", sep = '\n')
cat("     3         : Electrical Conductivity of soil saturation extract at which crop starts to be affected by soil salinity (dS/m)", sep = '\n')
cat("    11         : Electrical Conductivity of soil saturation extract at which crop can no longer grow (dS/m)", sep = '\n')
cat("    -9         : Dummy - no longer applicable", sep = '\n')
cat("    25         : Calibrated distortion (Percent) of CC due to salinity stress (Range: 0 (none) to +100 (very strong))", sep = '\n')
cat("   100         : Calibrated response (Percent) of stomata stress to ECsw (Range: 0 (none) to +200 (extreme))", sep = '\n')
cat(paste0(sprintf("     %1.2f", crop_params_aquacrop$Kc), "      : Crop coefficient when canopy is complete but prior to senescence (KcTr,x)"), sep = '\n')
cat("     0.150     : Decline of crop coefficient (Percent/day) as a result of ageing, nitrogen deficiency, etc.", sep = '\n')
cat("     0.15      : Minimum effective rooting depth (m)", sep = '\n')
cat(paste0(sprintf("     %1.2f", crop_params_aquacrop$Zr),"      : Maximum effective rooting depth (m)"), sep = '\n')
cat("    25         : Shape factor describing root zone expansion", sep = '\n')
cat("     0.048     : Maximum root water extraction (m3water/m3soil.day) in top quarter of root zone", sep = '\n')
cat("     0.012     : Maximum root water extraction (m3water/m3soil.day) in bottom quarter of root zone", sep = '\n')
cat("    50         : Effect of canopy cover in reducing soil evaporation in late season stage", sep = '\n')
cat("     3.00      : Soil surface covered by an individual seedling at 90 Percent emergence (cm2)", sep = '\n')
cat("     3.00      : Canopy size of individual plant (re-growth) at 1st day (cm2)", sep = '\n')
cat(paste0(sprintf("  %1.0f", crop_params_aquacrop$NPLDS), "      : Number of plants per hectare"), sep = '\n')
cat(paste0(sprintf("     %1.5f", crop_params_aquacrop$CGC),"   : Canopy growth coefficient (CGC): Increase in canopy cover (fraction soil cover per day)"), sep = '\n')
cat("    -9         : Maximum decrease of Canopy Growth Coefficient in and between seasons - Not Applicable", sep = '\n')
cat("    -9         : Number of seasons at which maximum decrease of Canopy Growth Coefficient is reached - Not Applicable", sep = '\n')
cat("    -9.0       : Shape factor for decrease Canopy Growth Coefficient - Not Applicable", sep = '\n')
cat(paste0(sprintf("     %1.2f", crop_params_aquacrop$CCx), "      : Maximum canopy cover (CCx) in fraction soil cover"), sep = '\n')
cat(paste0(sprintf("     %1.5f", crop_params_aquacrop$CDC), "   : Canopy decline coefficient (CDC): Decrease in canopy cover (in fraction per day)"), sep = '\n')
cat("     4         : Calendar Days: from sowing to emergence", sep = '\n')
cat("    65         : Calendar Days: from sowing to maximum rooting depth", sep = '\n')
cat("   108         : Calendar Days: from sowing to start senescence", sep = '\n')
cat("   158         : Calendar Days: from sowing to maturity (length of crop cycle)", sep = '\n')
cat("    96         : Calendar Days: from sowing to flowering", sep = '\n')
cat("    29         : Length of the flowering stage (days)", sep = '\n')
cat("     1         : Crop determinancy linked with flowering", sep = '\n')
cat("   100         : Excess of potential fruits (Percent)", sep = '\n')
cat("    57         : Building up of Harvest Index starting at flowering (days)", sep = '\n')
cat(paste0(sprintf("    %1.1f", crop_params_aquacrop$WP), "       : Water Productivity normalized for ETo and CO2 (WP) (gram/m2)"), sep = '\n')
cat("   100         : Water Productivity normalized for ETo and CO2 during yield formation (as Percent WP)", sep = '\n')
cat("    50         : Crop performance under elevated atmospheric CO2 concentration (Percent)", sep = '\n')
cat(paste0(sprintf("    %1.0f", crop_params_aquacrop$HIo), "         : Reference Harvest Index (HIo) (Percent)"), sep = '\n')
cat("     0         : Possible increase (Percent) of HI due to water stress before flowering", sep = '\n')
cat("    10.0       : Coefficient describing positive impact on HI of restricted vegetative growth during yield formation", sep = '\n')
cat("     7.0       : Coefficient describing negative impact on HI of stomatal closure during yield formation", sep = '\n')
cat("    15         : Allowable maximum increase (Percent) of specified HI", sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_emergence), "         : GDDays: from sowing to emergence"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_CCx), "         : GDDays: from sowing to maximum rooting depth"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_senecence),"         : GDDays: from sowing to start senescence"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_M),"         : GDDays: from sowing to maturity (length of crop cycle)"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_FL),"         : GDDays: from sowing to flowering"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_FLL),"         : Length of the flowering stage (growing degree days)"), sep = '\n')
cat(paste0(sprintf("     %1.5f", crop_params_aquacrop$CGC),"   : CGC for GGDays: Increase in canopy cover (in fraction soil cover per growing-degree day)"), sep = '\n')
cat(paste0(sprintf("     %1.5f", crop_params_aquacrop$CDC), "   : CDC for GGDays: Decrease in canopy cover (in fraction per growing-degree day)"), sep = '\n')
cat(paste0(sprintf("%6.0f", crop_params_aquacrop$GDD_HI),"         : GDDays: building-up of Harvest Index during yield formation"), sep = '\n')

sink()

}
